services:
  - type: web
    name: buildbyhet-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: TO_EMAIL
        value: hetpatelsk@gmail.com
      - key: PYTHON_VERSION
        value: 3.11.0
